export { default as BonameCrudPage } from './boname'
export type { BonameCrudPageProps, BonameRecord } from './boname'
export { default as DepositosCrudPage } from './depositos'
export type { DepositosCrudPageProps, DepositoRecord } from './depositos'
export { DemandasEspecificasCrudPage } from './demandas-especificas'
export type {
  DemandaEspecificaItemRecord,
  DemandaEspecificaRecord,
  DemandasEspecificasCrudPageProps,
} from './demandas-especificas'
export { default as EntradaMercadoriaDemandasCrudPage } from './entrada-mercadoria-demandas'
export { default as EstoqueListPage } from './estoque'
export type { EstoqueListPageProps, EstoqueRecord } from './estoque'
export { ConsultaMovimentacoesPage } from './estoque'
export type { ConsultaMovimentacoesPageProps, MovimentacaoRecord } from './estoque'
export { NovaSolicitacaoTransferenciaPage } from './estoque'
export type { NovaSolicitacaoTransferenciaPageProps } from './estoque'
export { default as FornecedoresCrudPage } from './fornecedores'
export type { FornecedorRecord, FornecedoresCrudPageProps } from './fornecedores'
export { default as EntradasCrudPage } from './entradas'
export type { EntradaFormValues, EntradaListItem, EntradasCrudPageProps } from './entradas'
export { default as ListarEntradasPage } from './ListarEntradasPage'
export { default as AprovacaoEntradasCrudPage } from './entradas/AprovacaoEntradasCrudPage'
export type { AprovacaoEntradasCrudPageProps, EntradaNaoAprovadaRecord } from './entradas/AprovacaoEntradasCrudPage'
export { default as DiagnosticosCrudPage } from './diagnosticos'
export type { DiagnosticosCrudPageProps, DiagnosticoRecord } from './diagnosticos'
export { default as LocaisRequisicaoCrudPage } from './locais-requisicao'
export type { LocalRequisicaoRecord, LocaisRequisicaoCrudPageProps } from './locais-requisicao'
export { default as MedicamentosCrudPage } from './medicamentos'
export type { MedicamentoRecord, MedicamentosCrudPageProps } from './medicamentos'
export { PacientesAmbulatorioCrudPage } from './pacientes'
export type { PacientesAmbulatorioCrudPageProps } from './pacientes'
export { default as AprovacaoRequisicaoPage } from './requisicoes/aprovacao'
export type { AprovacaoRequisicaoPageProps, RequisicaoNaoAprovadaRecord } from './requisicoes/aprovacao'
export { default as ControleDoseDomiciliarPage } from './requisicoes/controle-dose-domiciliar'
export type { ControleDDUItemRecord, ControleDDURecord, ControleDoseDomiciliarPageProps } from './requisicoes/controle-dose-domiciliar'
export { default as DevolucaoMedicamentoPage } from './requisicoes/devolucao-medicamento'
export { default as RequisicaoPorPacientePage } from './requisicoes/por-paciente'
export { default as TiposMedicamentosCrudPage } from './tipos-medicamentos'
export type { TiposMedicamentosCrudPageProps, TipoMedicamentoRecord } from './tipos-medicamentos'
